// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic.client.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendMessageReq struct {
	MessageId            string       `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReceiverType         ReceiverType `protobuf:"varint,2,opt,name=receiver_type,json=receiverType,proto3,enum=pb.ReceiverType" json:"receiver_type,omitempty"`
	ReceiverId           int64        `protobuf:"varint,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ToUserIds            []int64      `protobuf:"varint,4,rep,packed,name=to_user_ids,json=toUserIds,proto3" json:"to_user_ids,omitempty"`
	MessageBody          *MessageBody `protobuf:"bytes,5,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	SendTime             int64        `protobuf:"varint,6,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	IsPersist            bool         `protobuf:"varint,7,opt,name=is_persist,json=isPersist,proto3" json:"is_persist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendMessageReq) Reset()         { *m = SendMessageReq{} }
func (m *SendMessageReq) String() string { return proto.CompactTextString(m) }
func (*SendMessageReq) ProtoMessage()    {}
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d93363781e4ea5, []int{0}
}

func (m *SendMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageReq.Unmarshal(m, b)
}
func (m *SendMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageReq.Marshal(b, m, deterministic)
}
func (m *SendMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageReq.Merge(m, src)
}
func (m *SendMessageReq) XXX_Size() int {
	return xxx_messageInfo_SendMessageReq.Size(m)
}
func (m *SendMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageReq proto.InternalMessageInfo

func (m *SendMessageReq) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *SendMessageReq) GetReceiverType() ReceiverType {
	if m != nil {
		return m.ReceiverType
	}
	return ReceiverType_RT_UNKNOWN
}

func (m *SendMessageReq) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *SendMessageReq) GetToUserIds() []int64 {
	if m != nil {
		return m.ToUserIds
	}
	return nil
}

func (m *SendMessageReq) GetMessageBody() *MessageBody {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

func (m *SendMessageReq) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *SendMessageReq) GetIsPersist() bool {
	if m != nil {
		return m.IsPersist
	}
	return false
}

type SendMessageResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResp) Reset()         { *m = SendMessageResp{} }
func (m *SendMessageResp) String() string { return proto.CompactTextString(m) }
func (*SendMessageResp) ProtoMessage()    {}
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d93363781e4ea5, []int{1}
}

func (m *SendMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResp.Unmarshal(m, b)
}
func (m *SendMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResp.Marshal(b, m, deterministic)
}
func (m *SendMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResp.Merge(m, src)
}
func (m *SendMessageResp) XXX_Size() int {
	return xxx_messageInfo_SendMessageResp.Size(m)
}
func (m *SendMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendMessageReq)(nil), "pb.SendMessageReq")
	proto.RegisterType((*SendMessageResp)(nil), "pb.SendMessageResp")
}

func init() { proto.RegisterFile("logic.client.proto", fileDescriptor_68d93363781e4ea5) }

var fileDescriptor_68d93363781e4ea5 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4e, 0xc3, 0x30,
	0x10, 0x84, 0xe5, 0x04, 0x4a, 0xb3, 0xe9, 0x0f, 0xf8, 0x64, 0x81, 0x00, 0xab, 0x27, 0x9f, 0x72,
	0x08, 0xe2, 0x05, 0xb8, 0xf5, 0x80, 0x84, 0x4c, 0x39, 0x47, 0x24, 0x5e, 0x55, 0x96, 0x9a, 0xd8,
	0x64, 0x0d, 0x52, 0x9e, 0x84, 0xd7, 0x45, 0xf9, 0x29, 0xd0, 0xe3, 0x7c, 0x63, 0x6b, 0x66, 0x07,
	0xf8, 0xc1, 0xed, 0x6d, 0x95, 0x55, 0x07, 0x8b, 0x4d, 0xc8, 0x7c, 0xeb, 0x82, 0xe3, 0x91, 0x2f,
	0xaf, 0x97, 0x35, 0x12, 0xbd, 0xef, 0x71, 0x44, 0x9b, 0xef, 0x08, 0x56, 0xaf, 0xd8, 0x98, 0xe7,
	0x91, 0x6a, 0xfc, 0xe0, 0xb7, 0x00, 0xd3, 0x9b, 0xc2, 0x1a, 0xc1, 0x24, 0x53, 0x89, 0x4e, 0x26,
	0xb2, 0x35, 0xfc, 0x11, 0x96, 0x2d, 0x56, 0x68, 0xbf, 0xb0, 0x2d, 0x42, 0xe7, 0x51, 0x44, 0x92,
	0xa9, 0x55, 0x7e, 0x99, 0xf9, 0x32, 0xd3, 0x93, 0xb1, 0xeb, 0x3c, 0xea, 0x45, 0xfb, 0x4f, 0xf1,
	0x7b, 0x48, 0x7f, 0xbf, 0x59, 0x23, 0x62, 0xc9, 0x54, 0xac, 0xe1, 0x88, 0xb6, 0x86, 0xdf, 0x41,
	0x1a, 0x5c, 0xf1, 0x49, 0x83, 0x4f, 0xe2, 0x4c, 0xc6, 0x2a, 0xd6, 0x49, 0x70, 0x6f, 0xd4, 0xdb,
	0xc4, 0x73, 0x58, 0x1c, 0x6b, 0x95, 0xce, 0x74, 0xe2, 0x5c, 0x32, 0x95, 0xe6, 0xeb, 0x3e, 0x76,
	0x2a, 0xff, 0xe4, 0x4c, 0xa7, 0xd3, 0xfa, 0x4f, 0xf0, 0x1b, 0x48, 0x08, 0x1b, 0x53, 0x04, 0x5b,
	0xa3, 0x98, 0x0d, 0x91, 0xf3, 0x1e, 0xec, 0x6c, 0x8d, 0xfd, 0x9d, 0x96, 0x0a, 0x8f, 0x2d, 0x59,
	0x0a, 0xe2, 0x42, 0x32, 0x35, 0xd7, 0x89, 0xa5, 0x97, 0x11, 0x6c, 0xae, 0x60, 0x7d, 0x32, 0x0c,
	0xf9, 0x72, 0x36, 0x6c, 0xf6, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0x47, 0xf2, 0xc1, 0xd7, 0x5c,
	0x01, 0x00, 0x00,
}
