// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tcp.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PackageType int32

const (
	PackageType_PT_UNKNOWN   PackageType = 0
	PackageType_PT_SIGN_IN   PackageType = 1
	PackageType_PT_SYNC      PackageType = 2
	PackageType_PT_HEARTBEAT PackageType = 3
	PackageType_PT_MESSAGE   PackageType = 4
)

var PackageType_name = map[int32]string{
	0: "PT_UNKNOWN",
	1: "PT_SIGN_IN",
	2: "PT_SYNC",
	3: "PT_HEARTBEAT",
	4: "PT_MESSAGE",
}

var PackageType_value = map[string]int32{
	"PT_UNKNOWN":   0,
	"PT_SIGN_IN":   1,
	"PT_SYNC":      2,
	"PT_HEARTBEAT": 3,
	"PT_MESSAGE":   4,
}

func (x PackageType) String() string {
	return proto.EnumName(PackageType_name, int32(x))
}

func (PackageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{0}
}

// 请求的信息
type Input struct {
	Type                 PackageType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PackageType" json:"type,omitempty"`
	RequestId            int64       `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data                 []byte      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetType() PackageType {
	if m != nil {
		return m.Type
	}
	return PackageType_PT_UNKNOWN
}

func (m *Input) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Input) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 响应的信息
type Output struct {
	Type                 PackageType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PackageType" json:"type,omitempty"`
	RequestId            int64       `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code                 int32       `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Message              string      `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []byte      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{1}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetType() PackageType {
	if m != nil {
		return m.Type
	}
	return PackageType_PT_UNKNOWN
}

func (m *Output) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Output) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Output) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Output) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 设备登录,package_type:1
type SignInInput struct {
	AppId                int64    `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInInput) Reset()         { *m = SignInInput{} }
func (m *SignInInput) String() string { return proto.CompactTextString(m) }
func (*SignInInput) ProtoMessage()    {}
func (*SignInInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{2}
}

func (m *SignInInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInInput.Unmarshal(m, b)
}
func (m *SignInInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInInput.Marshal(b, m, deterministic)
}
func (m *SignInInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInInput.Merge(m, src)
}
func (m *SignInInput) XXX_Size() int {
	return xxx_messageInfo_SignInInput.Size(m)
}
func (m *SignInInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInInput.DiscardUnknown(m)
}

var xxx_messageInfo_SignInInput proto.InternalMessageInfo

func (m *SignInInput) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *SignInInput) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *SignInInput) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SignInInput) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 消息同步请求,package_type:2
type SyncInput struct {
	Seq                  int64    `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInput) Reset()         { *m = SyncInput{} }
func (m *SyncInput) String() string { return proto.CompactTextString(m) }
func (*SyncInput) ProtoMessage()    {}
func (*SyncInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{3}
}

func (m *SyncInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInput.Unmarshal(m, b)
}
func (m *SyncInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInput.Marshal(b, m, deterministic)
}
func (m *SyncInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInput.Merge(m, src)
}
func (m *SyncInput) XXX_Size() int {
	return xxx_messageInfo_SyncInput.Size(m)
}
func (m *SyncInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInput.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInput proto.InternalMessageInfo

func (m *SyncInput) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

// 消息同步响应,package_type:2
type SyncOutput struct {
	Messages             []*MessageItem `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SyncOutput) Reset()         { *m = SyncOutput{} }
func (m *SyncOutput) String() string { return proto.CompactTextString(m) }
func (*SyncOutput) ProtoMessage()    {}
func (*SyncOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{4}
}

func (m *SyncOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncOutput.Unmarshal(m, b)
}
func (m *SyncOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncOutput.Marshal(b, m, deterministic)
}
func (m *SyncOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncOutput.Merge(m, src)
}
func (m *SyncOutput) XXX_Size() int {
	return xxx_messageInfo_SyncOutput.Size(m)
}
func (m *SyncOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SyncOutput proto.InternalMessageInfo

func (m *SyncOutput) GetMessages() []*MessageItem {
	if m != nil {
		return m.Messages
	}
	return nil
}

// 消息投递,package_type:4
type Message struct {
	Message              *MessageItem `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{5}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() *MessageItem {
	if m != nil {
		return m.Message
	}
	return nil
}

// 投递消息回执,package_type:4
type MessageACK struct {
	DeviceAck            int64    `protobuf:"varint,2,opt,name=device_ack,json=deviceAck,proto3" json:"device_ack,omitempty"`
	ReceiveTime          int64    `protobuf:"varint,3,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageACK) Reset()         { *m = MessageACK{} }
func (m *MessageACK) String() string { return proto.CompactTextString(m) }
func (*MessageACK) ProtoMessage()    {}
func (*MessageACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{6}
}

func (m *MessageACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageACK.Unmarshal(m, b)
}
func (m *MessageACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageACK.Marshal(b, m, deterministic)
}
func (m *MessageACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageACK.Merge(m, src)
}
func (m *MessageACK) XXX_Size() int {
	return xxx_messageInfo_MessageACK.Size(m)
}
func (m *MessageACK) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageACK.DiscardUnknown(m)
}

var xxx_messageInfo_MessageACK proto.InternalMessageInfo

func (m *MessageACK) GetDeviceAck() int64 {
	if m != nil {
		return m.DeviceAck
	}
	return 0
}

func (m *MessageACK) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.PackageType", PackageType_name, PackageType_value)
	proto.RegisterType((*Input)(nil), "pb.Input")
	proto.RegisterType((*Output)(nil), "pb.Output")
	proto.RegisterType((*SignInInput)(nil), "pb.SignInInput")
	proto.RegisterType((*SyncInput)(nil), "pb.SyncInput")
	proto.RegisterType((*SyncOutput)(nil), "pb.SyncOutput")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*MessageACK)(nil), "pb.MessageACK")
}

func init() { proto.RegisterFile("tcp.proto", fileDescriptor_5d2504774879b91c) }

var fileDescriptor_5d2504774879b91c = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x41, 0x8b, 0xd3, 0x40,
	0x18, 0x35, 0x4d, 0xd3, 0x6e, 0xbe, 0xd4, 0x35, 0x0c, 0x8a, 0x41, 0x59, 0x88, 0xf1, 0x12, 0x15,
	0x7a, 0x50, 0x2f, 0x1e, 0xe3, 0x52, 0xd6, 0x61, 0xd9, 0x6c, 0x49, 0x22, 0x22, 0x08, 0x61, 0x3a,
	0xf3, 0x51, 0x42, 0x69, 0x3a, 0xdb, 0x4c, 0x16, 0xfa, 0x27, 0xfc, 0xcd, 0x32, 0x99, 0xe9, 0x6e,
	0x0f, 0x1e, 0xf7, 0xf6, 0xbd, 0xf7, 0xbe, 0xe4, 0xbd, 0xef, 0x25, 0xe0, 0x2b, 0x2e, 0xe7, 0x72,
	0xbf, 0x53, 0x3b, 0x32, 0x92, 0xab, 0x37, 0xcf, 0xb7, 0xd8, 0x75, 0x6c, 0x8d, 0x86, 0x4a, 0x6a,
	0xf0, 0x68, 0x2b, 0x7b, 0x45, 0xde, 0xc3, 0x58, 0x1d, 0x24, 0x46, 0x4e, 0xec, 0xa4, 0xe7, 0x9f,
	0x5f, 0xcc, 0xe5, 0x6a, 0xbe, 0x64, 0x7c, 0xc3, 0xd6, 0x58, 0x1d, 0x24, 0x16, 0x83, 0x48, 0x2e,
	0x00, 0xf6, 0x78, 0xd7, 0x63, 0xa7, 0xea, 0x46, 0x44, 0xa3, 0xd8, 0x49, 0xdd, 0xc2, 0xb7, 0x0c,
	0x15, 0x84, 0xc0, 0x58, 0x30, 0xc5, 0x22, 0x37, 0x76, 0xd2, 0x59, 0x31, 0xcc, 0xc9, 0x5f, 0x07,
	0x26, 0xb7, 0xbd, 0x7a, 0x42, 0x0b, 0xbe, 0x13, 0x38, 0x58, 0x78, 0xc5, 0x30, 0x93, 0x08, 0xa6,
	0xf6, 0xa8, 0x68, 0x1c, 0x3b, 0xa9, 0x5f, 0x1c, 0xe1, 0x43, 0x20, 0xef, 0x24, 0x90, 0x84, 0xa0,
	0x6c, 0xd6, 0x2d, 0x6d, 0xcd, 0xdd, 0xaf, 0x60, 0xc2, 0xa4, 0xd4, 0x5e, 0xce, 0xe0, 0xe5, 0x31,
	0x29, 0xa9, 0x20, 0x6f, 0xc1, 0x17, 0x78, 0xdf, 0x70, 0x7c, 0x4c, 0x71, 0x66, 0x08, 0x2a, 0xc8,
	0x6b, 0x98, 0xf6, 0x1d, 0xee, 0xb5, 0xe4, 0x0e, 0xd2, 0x44, 0x43, 0x2a, 0xc8, 0x4b, 0xf0, 0xd4,
	0x6e, 0x83, 0xad, 0xcd, 0x61, 0x40, 0x72, 0x01, 0x7e, 0x79, 0x68, 0xb9, 0xf1, 0x0b, 0xc1, 0xed,
	0xf0, 0xce, 0x9a, 0xe9, 0x31, 0xf9, 0x06, 0xa0, 0x65, 0x5b, 0xd2, 0x27, 0x38, 0xb3, 0xe9, 0xbb,
	0xc8, 0x8d, 0xdd, 0x34, 0x30, 0x45, 0xdd, 0x18, 0x8e, 0x2a, 0xdc, 0x16, 0x0f, 0x0b, 0xc9, 0x57,
	0x98, 0x5a, 0x81, 0x7c, 0x78, 0x2c, 0x41, 0xbf, 0xfb, 0x3f, 0x8f, 0x1d, 0xf5, 0x24, 0x07, 0xb0,
	0x7c, 0x76, 0x79, 0xad, 0x0b, 0xb7, 0x97, 0x32, 0xbe, 0x39, 0x16, 0x6e, 0x98, 0x8c, 0x6f, 0xc8,
	0x3b, 0x98, 0xed, 0x91, 0x63, 0x73, 0x8f, 0xb5, 0x6a, 0xb6, 0x68, 0x0f, 0x0e, 0x2c, 0x57, 0x35,
	0x5b, 0xfc, 0xf8, 0x07, 0x82, 0x93, 0xef, 0x48, 0xce, 0x01, 0x96, 0x55, 0xfd, 0x33, 0xbf, 0xce,
	0x6f, 0x7f, 0xe5, 0xe1, 0x33, 0x8b, 0x4b, 0x7a, 0x95, 0xd7, 0x34, 0x0f, 0x1d, 0x12, 0xc0, 0x54,
	0xe3, 0xdf, 0xf9, 0x65, 0x38, 0x22, 0x21, 0xcc, 0x96, 0x55, 0xfd, 0x63, 0x91, 0x15, 0xd5, 0xf7,
	0x45, 0x56, 0x85, 0xae, 0x5d, 0xbf, 0x59, 0x94, 0x65, 0x76, 0xb5, 0x08, 0xc7, 0xab, 0xc9, 0xf0,
	0xa3, 0x7e, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x21, 0xa7, 0x43, 0x29, 0xc8, 0x02, 0x00, 0x00,
}
